config/routes.rb
Rails.application.routes.draw do
  resources :ballots
  resources :awards
  get 'picks/edit', to: 'picks#edit', as: 'edit_picks'
  put 'picks', to: 'picks#update'
  resources :picks
  resources :nominations
  resources :categories
  resources :shows
  resources :games
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

  get 'dashboard/:id', to: 'users#dashboard', as: 'dashboard'
  
  root 'users#dashboard'
  
  get 'rules' => 'welcome#rules'
  

end

app/models/user.rb
class User < ApplicationRecord
  # require 'encrypter'
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_one :ballot #, -> { where(game_id: @current_game.id) }
  has_many :picks, through: :ballot
  accepts_nested_attributes_for :picks
  
  def total_points
    total_points = 0
    self.picks.each do |p|
      winner = Award.find(p.award.id).winner
      if p.first_pick == winner
        total_points += 3
      elsif p.second_pick == winner
        total_points += 2
      elsif p.third_pick == winner
        total_points += 1
      end
    end
    total_points
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      @users = User.where(email:params[:search]) || User.all
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to dashboard_url, notice: "Welcome to Awards Night, #{@user.fname}." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def dashboard
    if @current_user.nil?
      redirect_to login_url
      return
    end
    if @current_user.ballot.nil?
      redirect_to new_ballot_url
    end
    @awards = @current_show.awards
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :fname)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>Please fix the errors listed below:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, "First Name" %>
    <%= f.text_field :fname %>
  </div>
  
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Account' %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h2>Your Picks</h2>

<% @current_user.ballot.picks.each do |pick| %>

  <h3><%= pick.award.category.name %></h3>
    <%= pick.first_pick.nominee %> (3 pts)</br>
    <%= pick.second_pick.nominee %> (2 pts)</br>
    <%= pick.third_pick.nominee %> (1 pt)</br>
  
<% end %>

<p>You currently have <%=@current_user.total_points%> points.</p>
<p>You are in <%= User.count.ordinalize %> place out of <%= User.count %> player(s).</p>

<%= link_to 'Edit Picks', edit_ballot_path(@current_user.ballot) %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= params.inspect %>
<%= form_tag(users_path, :method => 'GET') do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= render 'form', user: @user %>

<%= button_to 'Back', root_path, method: :get %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>