config/routes.rb
Rails.application.routes.draw do
  resources :ballots
  resources :awards
  get 'picks/edit', to: 'picks#edit', as: 'edit_picks'
  put 'picks', to: 'picks#update'
  resources :picks
  resources :nominations
  resources :categories
  resources :shows
  resources :games
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

  get 'dashboard/:id', to: 'users#dashboard', as: 'dashboard'
  
  root 'users#dashboard'
  
  get 'rules' => 'welcome#rules'
  

end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :show
  belongs_to :category
  has_many :nominations
  belongs_to :winner, :class_name => "Nomination", :foreign_key => "winner_id"
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :set_award, only: [:show, :edit, :update, :destroy]

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.fetch(:award, {})
    end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_for(award) do |f| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= link_to 'Show', award %></td>
        <td><%= link_to 'Edit', edit_award_path(award) %></td>
        <td><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Award', new_award_path %>

app/views/awards/new.html.erb
<h1>New Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>