config/routes.rb
Rails.application.routes.draw do
  resources :ballots
  resources :awards
  get 'picks/edit', to: 'picks#edit', as: 'edit_picks'
  put 'picks', to: 'picks#update'
  resources :picks
  resources :nominations
  resources :categories
  resources :shows
  resources :games
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

  get 'dashboard/:id', to: 'users#dashboard', as: 'dashboard'
  
  root 'users#dashboard'
  
  get 'rules' => 'welcome#rules'
  

end

app/models/pick.rb
class Pick < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :award
  belongs_to :ballot
  belongs_to :first_pick, :class_name => "Nomination", :foreign_key => 'first_pick_id'
  belongs_to :second_pick, :class_name => 'Nomination', :foreign_key => 'second_pick_id'
  belongs_to :third_pick, :class_name => 'Nomination', :foreign_key => 'third_pick_id'
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_form.html.erb
<h1>2017 Academy Awards Ballot</h1>

<%= link_to 'Rules', rules_path %>

<%= form_tag picks_path do %>
  <% @awards.each do |award| %>
    <%= fields_for 'picks[][]', pick do |p| %>

      <%= hidden_field_tag "picks[][user_id]", 1 %>
      <%= hidden_field_tag "picks[][game_id]", 1 %>
      <%= hidden_field_tag "picks[][award_id]", award.id %>
    
      <h2><%= award.category.name %></h2>
      
      <div class="field">
        <%= p.label :first_pick, "First Pick: 3 points" %>
        <%= p.collection_select(:first_pick, award.nominations, :id, :nominee) %>
      </div>
      <div class="field">
        <%= p.label :second_pick, "Second Pick: 2 points" %>
        <%= p.collection_select(:second_pick, award.nominations, :id, :nominee) %>
      </div>
      <div class="field">
        <%= p.label :third_pick, "Third Pick: 1 point" %>
        <%= p.collection_select(:third_pick, award.nominations, :id, :nominee) %>
      </div>

    <% end %>
  <% end %>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

  

app/views/picks/edit.html.erb
<h1>2017 Academy Awards Ballot</h1>

<%= link_to 'Rules', rules_path %>


<%= form_tag picks_path, :method => :put do %>
  <% @picks.each do |pick| %>
    <%= fields_for "picks[]", pick do |p| %>

      <h2><%= pick.award.category.name %></h2>
      
      <div class="field">
        <%= p.label :first_pick, "First Pick: 3 points" %>
        <%= p.collection_select(:first_pick, pick.award.nominations, :id, :nominee) %>
      </div>
      <div class="field">
        <%= p.label :second_pick, "Second Pick: 2 points" %>
        <%= p.collection_select(:second_pick, pick.award.nominations, :id, :nominee) %>
      </div>
      <div class="field">
        <%= p.label :third_pick, "Third Pick: 1 point" %>
        <%= p.collection_select(:third_pick, pick.award.nominations, :id, :nominee) %>
      </div>

    <% end %>
  <% end %>
  <div class="actions">
    <%= submit_tag "Update Ballot" %>
  </div>
<% end %>

  

app/views/picks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Picks</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>User</th>
      <th>Nomination</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picks.each do |pick| %>
      <tr>
        <td><%= pick.game %></td>
        <td><%= pick.user %></td>
        <td><%= pick.nomination %></td>
        <td><%= pick.value %></td>
        <td><%= link_to 'Show', pick %></td>
        <td><%= link_to 'Edit', edit_pick_path(pick) %></td>
        <td><%= link_to 'Destroy', pick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pick', new_pick_path %>

app/views/picks/new.html.erb
<%= render 'form', pick: @pick %>

<%= link_to 'Back', picks_path %>

app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @pick.game %>
</p>

<p>
  <strong>User:</strong>
  <%= @pick.user %>
</p>

<p>
  <strong>Nomination:</strong>
  <%= @pick.nomination %>
</p>

<p>
  <strong>Value:</strong>
  <%= @pick.value %>
</p>

<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>